# Generated by Django 6.0 on 2025-12-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_update_halfvec_to_768'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentchunk',
            name='unique_document_chunk',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='documents_d_documen_8ea6ce_idx',
            old_name='documents_d_documen_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
